custom: ${file(../customs/${opt:stage, 'dev'}.yml)}

service: serverless-cognito-login

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  region: ${self:custom.deployRegion}
  profile: ${self:custom.profile}

resources:
  Resources:
    CognitoUserPool:  # Cognitoユーザープール
      Type: AWS::Cognito::UserPool
      Properties:
        UsernameAttributes:
          - 'email'
        Policies:
          PasswordPolicy:
            MinimumLength: 10
            RequireUppercase: false
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: true
        UserPoolName: serverless-cognito-login-userpool
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: false
          UnusedAccountValidityDays: 7
        Schema:
          - Name: email
            AttributeDataType: String
            DeveloperOnlyAttribute: false
            Mutable: false
            Required: true

    UserPoolClient:  # アプリクライアント
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: serverless-cognito-login-client
        ExplicitAuthFlows:
          - ADMIN_NO_SRP_AUTH
        GenerateSecret: false
        RefreshTokenValidity: 1
        UserPoolId:
          Ref: CognitoUserPool

    IdentityPool:  # IDプール
      Type: AWS::Cognito::IdentityPool
      Properties:
        IdentityPoolName: serverless-cognito-login-idpool
        AllowUnauthenticatedIdentities: false
        CognitoIdentityProviders:
          - ClientId:
              Ref: UserPoolClient
            ProviderName:
              Fn::GetAtt:
                - CognitoUserPool
                - ProviderName

    UnauthenticatedPolicy:  # 認証されていないロールにアタッチするポリシー
      Type: AWS::IAM::ManagedPolicy
      Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - mobileanalytics:PutEvents
                - cognito-sync:*
              Resource:
                - '*'
    UnauthenticatedRole:  # 認証されていないロール
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: 'sts:AssumeRoleWithWebIdentity'
              Principal:
                Federated: cognito-identity.amazonaws.com
              Condition:
                StringEquals:
                  'cognito-identity.amazonaws.com:aud':
                    Ref: IdentityPool
                ForAnyValue:StringLike:
                  'cognito-identity.amazonaws.com:amr': unauthenticated
        ManagedPolicyArns:
          - Ref: UnauthenticatedPolicy
        RoleName:
          Fn::Join:
            - ''
            - - Fn::GetAtt:
                  - IdentityPool
                  - Name
              - Unauth_Role

    AuthenticatedPolicy:  # 認証されたロールにアタッチするポリシー
      Type: AWS::IAM::ManagedPolicy
      Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - mobileanalytics:PutEvents
                - cognito-sync:*
                - cognito-identity:*
              Resource:
                - '*'
    AuthenticatedRole:  # 認証されたロール
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action: 'sts:AssumeRoleWithWebIdentity'
              Principal:
                Federated: cognito-identity.amazonaws.com
              Condition:
                StringEquals:
                  'cognito-identity.amazonaws.com:aud':
                    Ref: IdentityPool
                ForAnyValue:StringLike:
                  'cognito-identity.amazonaws.com:amr': authenticated
        ManagedPolicyArns:
          - Ref: AuthenticatedPolicy
        RoleName:
          Fn::Join:
            - ''
            - - Fn::GetAtt:
                  - IdentityPool
                  - Name
              - Auth_Role

    IdentityPoolRoleAttachment:  # IDプールへのロールのアタッチ
      Type: AWS::Cognito::IdentityPoolRoleAttachment
      Properties:
        IdentityPoolId:
          Ref: IdentityPool
        Roles:
          unauthenticated:
            Fn::GetAtt:
              - UnauthenticatedRole
              - Arn
          authenticated:
            Fn::GetAtt:
              - AuthenticatedRole
              - Arn
