custom: ${file(../customs/${opt:stage, 'dev'}.yml)}

service: desktoday-user-server-me

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, 'dev'}
  region: ${self:custom.deployRegion}
  profile: ${self:custom.profile}
  logRetentionInDays: ${self:custom.retentionInDays}
  timeout: 30
  memorySize: 256
  logs:
    restApi: true
  tracing:
    apiGateway: true
    lambda: true
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "cognito-idp:AdminInitiateAuth"
      Resource:
        - "arn:aws:cognito-idp:us-west-2:913092107261:userpool/us-west-2_Slxlfcy74"

package:
  include:
    - common/**
  exclude:
    - tests/**

plugins:
  - serverless-prune-plugin

functions:
  user_auth:
    handler: src.auth_handler.user_auth_handler
    environment:
      COGNITO_CLIENT_ID: '7265qqlobva1shdbe9ncnn8pu7'
      USER_POOL_ID: 'us-west-2_Z3wdwfhSD'
    events:
      - http:
          path: /auth
          method: post

resources:
  Resources:
    ApiGatewayLogGroup:
      Properties:
        RetentionInDays: ${self:custom.retentionInDays}
